services:
  expenses_management_cli:
    container_name: expenses_management_cli
    image: ivansanchez93/purchase_management_cli
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: "production"
      PORT: 3000
    networks:
      - app_network
networks:
  app_network:
    name: purchasemanagement_app_network
    external: true
      